### ISSUE TITLE
WTS takes ZLD on exchange but didn't send BTC

### ISSUE THREAD

**Issue by g4s8** [zold-io/wts.zold.io#283]
I exchange ZLD to BTC, WTS takes ZLD from my wallet but didn't send BTC, also didn't post a message to Telegram channel.
My wallet is [3be3416c805e4371](http://www.zold.io/ledger.html?wallet=3be3416c805e4371)
Transaction id is `#100`, WTS job id is `929a50a5-4574-43­53-8d04-83fe3a5c­b506`
![scrot-2019-07-10-16:30:08](https://user-images.githubusercontent.com/1524988/60973098-3a193900-a330-11e9-9a80-281b72a95a62.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment]
@yegor256 ping, can you please check this bug?

**Comment by yegor256** [comment]
@g4s8 I suspect that the server was rebooted right in the middle of your payment processing... That's why we don't see the job here: https://wts.zold.io/output?id=929a50a5-4574-43­53-8d04-83fe3a5c­b506 and here https://wts.zold.io/log?id=929a50a5-4574-43­53-8d04-83fe3a5c­b506

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.42`

**Comment by yegor256** [comment]
@g4s8 I think I know what the problem was: pgtk 0.7.0 had a bug. it's fixed in 0.7.1. shouldn't happen again. I will send you 150 ZLD now.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#284](https://github.com/zold-io/wts.zold.io/issues/284) is still not solved.

**Comment by yegor256** [comment]
@rultor release, tag is `0.35.42`

**Comment by 0crat** [comment]
Job `gh:zold-io/wts.zold.io#283` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by g4s8** [comment]
@yegor256 thanks!
